export const LOAD_USERS = "LOAD_USERS";
export const LOAD_QUESTIONS = "LOAD_QUESTIONS";
export const SET_AUTH_USER ="SET_AUTH_USER";
export const ADD_QUESTION ="ADD_QUESTION";
export const ADD_QUESTION_TO_USER ="ADD_QUESTION_TO_USER";
export const ADD_NEW_ANSWER_TO_USER ="ADD_NEW_ANSWER_TO_USER";
export const ADD_NEW_ANSWER_TO_QUESTION ="ADD_NEW_ANSWER_TO_QUESTION";
export const UPDATE_AUTH = "UPDATE_AUTH"